services:
  empower_orphans_web:
    build: .
    container_name: empower_orphans_web
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=empowerorphans.com,www.empowerorphans.com
      - LETSENCRYPT_HOST=empowerorphans.com,www.empowerorphans.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_EMAIL=omarmgmi@gmail.com
    networks:
      - webnet

networks:
  webnet:
    external: true
